# Squeezing Tensor 
### means removing all dimensions that have size 1 from its shape to make it simpler, without changing the data.

In [1]:
import tensorflow as tf

In [2]:
tf.random.uniform(shape=[50])

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.3697666 , 0.29742837, 0.27105916, 0.04179788, 0.92452884,
       0.10960686, 0.02088809, 0.39933217, 0.3283403 , 0.6935861 ,
       0.68147707, 0.13794899, 0.93977857, 0.58479595, 0.71551955,
       0.34567988, 0.31026423, 0.19474566, 0.14890242, 0.36576116,
       0.6548716 , 0.8431417 , 0.08589935, 0.14545941, 0.48906803,
       0.6291343 , 0.01482952, 0.74412227, 0.61021996, 0.02241266,
       0.22678638, 0.15491772, 0.5504736 , 0.35177624, 0.297431  ,
       0.3382113 , 0.5986092 , 0.70112944, 0.7611748 , 0.40125132,
       0.8678651 , 0.39166832, 0.13370776, 0.9058013 , 0.34826398,
       0.42100108, 0.21353674, 0.41058493, 0.35770237, 0.94850624],
      dtype=float32)>

In [3]:
tf.random.set_seed(42)
tensor=tf.constant(tf.random.uniform(shape=[50]),shape=[1,1,1,1,50])

tensor

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [4]:
tensor.shape

TensorShape([1, 1, 1, 1, 50])

In [5]:
tensor_squuezed=tf.squeeze(tensor)

tensor_squuezed



<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [6]:
print("tensor Before squeezing:", tensor.shape)
print("\n")
print("tensor After squeezing:", tensor_squuezed.shape)

tensor Before squeezing: (1, 1, 1, 1, 50)


tensor After squeezing: (50,)


# Think of it like this:
### Squeezing is like removing empty boxes around your actual data — the data doesn’t change, just the shape becomes cleaner and more usable.