# Matrix Multiplication

In [1]:
import tensorflow as tf

In [2]:
tensor=tf.constant([[1,2],[3,4]])

tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [3]:
tf.linalg.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [4]:
# or we can also do like this
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

# Normal pythonic multiplication

In [5]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [6]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [8]:
# Practise 
mat1=tf.random.uniform(shape=(3,3))
mat2=tf.random.uniform(shape=(3,2))

tf.matmul(mat1, mat2)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.53244895, 0.9586939 ],
       [0.39622065, 0.5514575 ],
       [0.30586115, 0.44156602]], dtype=float32)>

# Matrix multiplication with python 

In [9]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [10]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [11]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

# wrong way of doing matrix multiplication

In [12]:
# Practise 
mat1=tf.random.uniform(shape=(3,2))
mat2=tf.random.uniform(shape=(3,2))

try:
    tf.matmul(mat1, mat2)
except Exception as e:
    print(f"Error: {e}")

Error: {{function_node __wrapped____MklMatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 


| Rule                                                
| --------------------------------------------------- 
| Only multiply A×B if A's **columns** = B's **rows**             
| Result shape = (A.rows, B.columns)                               
| Not commutative: A×B ≠ B×A (in general)             


In [13]:
mat1.shape, mat2.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [14]:
mat2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.17923021, 0.5267341 ],
       [0.11355913, 0.9038204 ],
       [0.5902103 , 0.779225  ]], dtype=float32)>

In [15]:
#Lets change the shape of mat2

tf.reshape(mat2, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.17923021, 0.5267341 , 0.11355913],
       [0.9038204 , 0.5902103 , 0.779225  ]], dtype=float32)>

In [16]:
mat1.shape,tf.reshape(mat2, shape=(2,3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [17]:
# Now can we do matmul
tf.matmul(mat1,tf.reshape(mat2, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.8669522 , 0.86636   , 0.71742105],
       [0.8579113 , 0.8161174 , 0.7140597 ],
       [0.93782955, 0.9814774 , 0.7716453 ]], dtype=float32)>

In [18]:
mat1.shape, mat2.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [19]:
tf.matmul(mat2, tf.reshape(mat1, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.5660804, 0.6203642, 0.564405 ],
       [0.8291843, 0.9066003, 0.847303 ],
       [1.0756415, 1.1823051, 1.0379832]], dtype=float32)>

# Transpose of a tensor

In [20]:
mat1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7328042 , 0.8138913 ],
       [0.62458014, 0.82534945],
       [0.9008156 , 0.8589939 ]], dtype=float32)>

In [21]:
# Transpose just flips the axes of the matrix
tf.transpose(mat1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.7328042 , 0.62458014, 0.9008156 ],
       [0.8138913 , 0.82534945, 0.8589939 ]], dtype=float32)>

In [22]:
tf.reshape(mat1, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.7328042 , 0.8138913 , 0.62458014],
       [0.82534945, 0.9008156 , 0.8589939 ]], dtype=float32)>

In [23]:
tf.linalg.matmul(tf.transpose(mat1), mat2)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.7339381, 1.6524394],
       [0.7465869, 1.8440216]], dtype=float32)>

### using tf.matmult() or tf.linalg.matmul() is the same

# We Can Perform matrix multiplication with tf.matmul() or tf.tensordot() or @ operator

In [24]:
print("Matrix 1 :",mat1)
print("\n")
print("Matrix 2 :",mat2)
print("\n")

Matrix 1 : tf.Tensor(
[[0.7328042  0.8138913 ]
 [0.62458014 0.82534945]
 [0.9008156  0.8589939 ]], shape=(3, 2), dtype=float32)


Matrix 2 : tf.Tensor(
[[0.17923021 0.5267341 ]
 [0.11355913 0.9038204 ]
 [0.5902103  0.779225  ]], shape=(3, 2), dtype=float32)




In [25]:
tf.matmul(tf.transpose(mat1), mat2)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.7339381, 1.6524394],
       [0.7465869, 1.8440216]], dtype=float32)>

In [26]:
tf.matmul(tf.reshape(mat1, shape=(2,3)), mat2)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.59239906, 1.608293  ],
       [0.75721043, 1.9182647 ]], dtype=float32)>

#### generally when performing matrix multiplication on two tensors and one of the axes doesn't line up ,you will transpose rather than reshape one of the tensors to get satisfy matrix multiplication rules.