# Aggregating tensors

### **Tensor aggregation** is the process of combining multiple tensor values into a single tensor using operations like sum, mean, or concatenation.


In [2]:
import tensorflow as tf

In [3]:
# get the absolute  value

tensor=tf.constant([-7,-10])

tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [4]:
tf.abs(tensor)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

# Element-wise aggregation

#### Aggregating values across dimensions using operations like:

* sum(): Sum all or specific dimensions.

* mean(): Average values along certain axes.

* max() / min(): Find maximum/minimum values.

In [5]:
# Create a tensor with random values between 1 to 100 of size 50
import numpy as np 
np_arr=np.random.randint(low=1,high=100,size=50)
tensor=tf.constant(np_arr)

tensor

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([37, 49, 51, 81, 77, 76, 97, 50, 66,  6, 53,  7, 47, 70, 37, 50, 96,
       31, 58, 34, 32,  2, 76, 78, 60, 58, 52, 11, 36, 69, 65, 18, 90, 46,
       95, 23, 31, 35, 53, 30, 25, 13, 39, 23, 52, 52, 44,  1, 64, 71],
      dtype=int32)>

In [6]:
tensor.shape,tensor.ndim,tf.size(tensor)

(TensorShape([50]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=50>)

In [7]:
# finding the minimum
tf.reduce_min(input_tensor=tensor,name="min value in tensor ## optional")

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [8]:
# finding maximu 
tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=97>

In [9]:
#finding the mean 
tf.reduce_mean(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=48>

In [10]:
tf.reduce_sum(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2417>

In [11]:
tensor

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([37, 49, 51, 81, 77, 76, 97, 50, 66,  6, 53,  7, 47, 70, 37, 50, 96,
       31, 58, 34, 32,  2, 76, 78, 60, 58, 52, 11, 36, 69, 65, 18, 90, 46,
       95, 23, 31, 35, 53, 30, 25, 13, 39, 23, 52, 52, 44,  1, 64, 71],
      dtype=int32)>

In [12]:
a = tf.constant([[1, 2]])
b = tf.constant([[3, 4]])

tf.concat([a,b],axis=0)  

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [13]:
tf.stack([a,b],axis=0)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[1, 2]],

       [[3, 4]]], dtype=int32)>



### 🔹 `tf.concat`: **Joins tensors along an existing axis**

* **Does not add a new dimension**
* Requires tensors to have the **same shape except** along the concatenation axis.

### 🔹 `tf.stack`: **Stacks tensors along a new axis**

* **Adds a new dimension**
* Requires all tensors to have **exactly the same shape**

### ✅ Summary

| Operation   | Adds new dimension? | Output shape (for a, b shape (1, 2)) |
| ----------- | ------------------- | ------------------------------------ |
| `tf.concat` | ❌ No                | `(2, 2)`                             |
| `tf.stack`  | ✅ Yes               | `(2, 1, 2)`                          |

Use:

* `concat` when you want to **combine** tensors *without changing the rank*.
* `stack` when you want to **group** tensors into a higher-dimensional tensor.


In [14]:
tensor

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([37, 49, 51, 81, 77, 76, 97, 50, 66,  6, 53,  7, 47, 70, 37, 50, 96,
       31, 58, 34, 32,  2, 76, 78, 60, 58, 52, 11, 36, 69, 65, 18, 90, 46,
       95, 23, 31, 35, 53, 30, 25, 13, 39, 23, 52, 52, 44,  1, 64, 71],
      dtype=int32)>

In [15]:
float_tensor=tf.cast(x=tensor,dtype=tf.float16)

float_tensor

<tf.Tensor: shape=(50,), dtype=float16, numpy=
array([37., 49., 51., 81., 77., 76., 97., 50., 66.,  6., 53.,  7., 47.,
       70., 37., 50., 96., 31., 58., 34., 32.,  2., 76., 78., 60., 58.,
       52., 11., 36., 69., 65., 18., 90., 46., 95., 23., 31., 35., 53.,
       30., 25., 13., 39., 23., 52., 52., 44.,  1., 64., 71.],
      dtype=float16)>

In [16]:
tf.math.reduce_std(float_tensor)

<tf.Tensor: shape=(), dtype=float16, numpy=24.84375>

In [17]:
tf.math.reduce_variance(float_tensor)

<tf.Tensor: shape=(), dtype=float16, numpy=617.5>