## Tensor Creation in TensorFlow

A tensor is the basic data structure used in TensorFlow. It is similar to a NumPy array and can store numerical data in different dimensions.

## Tensors can be created using:

      tf.constant() — creates a fixed tensor.
      tf.Variable() — creates a tensor whose values can be changed.
      tf.zeros() — creates a tensor filled with zeros.
      tf.ones() — creates a tensor filled with ones.
      tf.range() — creates a sequence of values.
      tf.random — creates tensors with random values.

In [8]:
import tensorflow as tf

In [3]:
# 1. tf.constant() - Fixed tensor
a = tf.constant([1, 2, 3])
print(a)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [4]:
# 2. tf.Variable() - Changeable tensor
b = tf.Variable([10, 20, 30])
b.assign([40, 50, 60])
print(b)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([40, 50, 60], dtype=int32)>


In [5]:
# 3. tf.zeros() - Tensor filled with zeros
c = tf.zeros(shape=(2, 3))
print(c)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [6]:
# 4. tf.ones() - Tensor filled with ones
d = tf.ones(shape=(2, 3))
print(d)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [7]:
# 5. tf.range() - Sequence of values
e = tf.range(start=0, limit=10, delta=2)
print(e)

tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)


In [9]:
# 6. tf.random - Random tensor
f = tf.random.uniform(shape=(2, 3))
print(f)

tf.Tensor(
[[0.510975   0.695431   0.5362835 ]
 [0.5049541  0.06290376 0.7395948 ]], shape=(2, 3), dtype=float32)


Remember: tf.constant() → fixed, tf.Variable() → changeable, tf.zeros() / tf.ones() → initialized tensors, tf.range() → sequence, tf.random → random values.

##### Key idea: A tensor can have different dimensions: Scalar (0D) → Vector (1D) → Matrix (2D) → Higher-dimensional Tensor (3D+)