# Tensors and Numpy 

## Why this is powerful:
NumPy = fast, flexible data handling

TensorFlow = powerful modeling + GPU acceleration

They work together seamlessly — no need to manually convert formats most of the time

In [1]:
import tensorflow as tf
import numpy as np

In [3]:
# Create a tensor directly from a numpy array 

np_array=np.array([[1,2,3],[4,5,6]])

tensor=tf.Variable(np_array)

tensor

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [4]:
np_arr = np.array([1, 2, 3, 4])
tf_tensor = tf.convert_to_tensor(np_arr)

print("Tensor:", tf_tensor)

Tensor: tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)


In [5]:
# Converts a tensor to a numpy array

np.array(tensor) , type(np.array(tensor))

C:\Users\HP\AppData\Local\Temp\ipykernel_4684\2960171324.py:3: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  np.array(tensor) , type(np.array(tensor))


(array([[1, 2, 3],
        [4, 5, 6]]),
 numpy.ndarray)

In [6]:
result = tf_tensor * 2       # TensorFlow operation
np_result = result.numpy()   # Back to NumPy

print("NumPy result:", np_result)

NumPy result: [2 4 6 8]


In [7]:
tensor = tf.constant([[1, 2], [3, 4]])

tensor.numpy()  # Converts the tensor to a NumPy array

array([[1, 2],
       [3, 4]], dtype=int32)

# ✅ Use NumPy for preprocessing, TensorFlow for modeling

In [8]:
# NumPy for normalizing data
data = np.random.rand(5, 3) * 100
normalized = (data - np.mean(data)) / np.std(data)

# Feed into TensorFlow
tf_input = tf.convert_to_tensor(normalized, dtype=tf.float32)
print(tf_input)

tf.Tensor(
[[-0.3889258   0.13271123  1.6534531 ]
 [-1.4446995  -1.194086   -0.509526  ]
 [ 0.3079988  -1.0247374   0.1407568 ]
 [ 1.3518739  -0.04599105  1.1483009 ]
 [ 0.10780326  1.2918508  -1.5267831 ]], shape=(5, 3), dtype=float32)


# ✅ Slicing and reshaping using NumPy and TensorFlow together

In [9]:
a = np.arange(12).reshape(3, 4)  # NumPy reshape
t = tf.convert_to_tensor(a)

# TensorFlow slicing
print(t[:, 1:3])

tf.Tensor(
[[ 1  2]
 [ 5  6]
 [ 9 10]], shape=(3, 2), dtype=int64)


# ✅ Training with NumPy data in a TensorFlow model

In [11]:
# NumPy data
x = np.random.rand(100, 1)
y = 3 * x + 2

# TensorFlow model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1, input_shape=(1,))
])

model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=3) 

Epoch 1/3
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 13.0007  
Epoch 2/3
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.9553 
Epoch 3/3
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.9114 
